name: environment_variables
on: [push]
env:
  APP_NAME: workflow-app

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: job-app
    steps:
      - name: building the steps
        env:
          APP_NAME: step-app
        run: echo "My name is ${APP_NAME}"
