name: sequntial-workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Build Steps started"
        
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Step
        run: echo "Testing step started"
        
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Deploying Started
        run: echo "Deploying Started"
        
      
